# Generated by Django 5.0.2 on 2024-03-05 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipebookapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
    ]
